### ISSUE TITLE
Aucun retour quand je teste la connectivité

### ISSUE THREAD

**Issue by pacormn** [Top-Serveurs/fivem-vote-plugin#11]
Bonjour, 
J'ai installé la V1 du plugin mais je ne recois rien alors que j'ai bien configuré un port ouvert (autre que celui de mon serveur) et j'ai bien remplis le token
Sur une autre machine il y quelques mois ca marchait mais quand je fais un test de vote ou de connexion, rien ne s'affiche.

Si quelqu'un a une réponse à ce problème ca serait top...

Merci

**Comment by Metrakit** [comment]
We are no longer supporting the v1 plugin, please take a look at our v2: https://github.com/Top-Serveurs/cfx-vote-plugin
