### ISSUE TITLE
Je ne reçois aucune réponse de l'API.

### ISSUE THREAD

**Issue by SNIKRS** [Top-Serveurs/fivem-vote-plugin#4]
Yo voila mon code que j'utilise pour les votes, je l'ai testé en dehors dans un de mes event et le code marchait, par contre si je le met dans ton event, RIEN. On peut meme pas debug psk faut attendre 1h pour voter (du coup, suggestion; ajouter un test vote dans le panel, évidemment un vote non compter sur le site mais qui fonctionne pour l'API.)

```lua
AddEventHandler('onPlayerVote', function(playername, ip, date)
    local Players = ESX.GetPlayers()
    local Player = getPlayerByName(playername)
    if Player then
        Player.addMoney(2500)
        for i=1, #xPlayers, 1 do
            TriggerClientEvent('esx:showAdvancedNotification', Players[i], "SantosRP", "Vote", playername.." à voté pour le serveur !\nIl à gagné ~g~2500$~w~", "CHAR_SOCIAL_CLUB", 4)
        end
    else
        print("Joueur introuvable !")
    end
    print(playername.." à voté pour le serveur ! "..ip.." | "..date)
end)
```

**Comment by meyervp** [comment]
ton problème est que d'origine dans le _resource.lua le fichier exemple_esx.lua n'est pas déclaré

`server_script {
    "example.lua",
    "example_esx.lua"
}`

**Comment by Metrakit** [comment]
Merci @meyervp . @SNIKRS nous venons de rajouter un bouton pour simuler un vote , si ça peux t'aider dans tes recherches : 

<img width="688" alt="Capture d’écran 2020-07-05 à 16 45 45" src="https://user-images.githubusercontent.com/3305600/86535238-2a024e00-bedf-11ea-802e-981ef3466527.png">

Tu n'as pas besoin d'attendre 2h avec ce bouton, cela simule simplement un vote sans le comptabiliser.

**Comment by meyervp** [comment]
cool bonne nouvelle !
