### ISSUE TITLE
Add money to offline player 

### ISSUE THREAD

**Issue by Krusty-01** [Top-Serveurs/fivem-vote-plugin#5]
Hello.

The script working good. 
But how can i add à money to a offline player if it's voting ?

Thanks

**Comment by meyervp** [comment]
Hi,

I invite you to look at my PR while we wait for Top Server to merge it.

https://github.com/Top-Serveurs/fivem-vote-plugin/pull/6/files

**Comment by Metrakit** [comment]
Thanks for your PR ! We will take a look then merge it.

**Comment by Metrakit** [comment]
@meyervp I merged your PR, @Krusty-01 I invite you to download the last version of the plugin. I close the issue.
