### ISSUE TITLE
Charge serveur importante

### ISSUE THREAD

**Issue by BlaiseLebreton** [Top-Serveurs/fivem-vote-plugin#7]
Hello ! 

Depuis l'arrivée des dernières version d'artifact serveur c'est possible de voir la consommation des ressources coté serveur.
J'ai donc regardé ceux qui consomment le plus et j'ai été un peu surpris de voir que 50% de la charge de mon serveur (qui est quand même plutôt chargé) est dû à ce plugin de vote.

Ce constat a été fait sur un serveur local sans aucun vote en cours. Je me sens obligé de couper cette ressource jusqu'à ce que ce soit résolu.

En espérant que vous pourrez optimiser la ressource ;) 
Bon courage.

![image](https://user-images.githubusercontent.com/59114761/100214171-d507b880-2f0f-11eb-94bc-5f023fac8be9.png)

**Comment by Metrakit** [comment]
Bonjour, on ne nous a jamais remonté des problèmes de performance concernant notre plugin de vote.
Je ne pense pas que cela à un impact important sur les serveurs FiveM.
Nous utilisons un système de sockets afin d'intercepter les votes via notre DLL et cela peut expliquer la consommation d'un peu de ressources, cependant ça reste minime car ce n'est pas une grosse feature.

Nous allons quand même nous pencher sur la question, merci pour le report.
