### ISSUE TITLE
Accents non pris en charge

### ISSUE THREAD

**Issue by Jim1120** [Top-Serveurs/fivem-vote-plugin#8]
Bonjour,
Je remarque que la variable Playername du plugin n'intègre pas les accents que les joueurs inscrivent dans le pseudo.
Avez vous une idée pour résoudre ce soucis ?
Merci d’avance

**Comment by Metrakit** [comment]
This plugin is deprecated, as explained in our documentation you have to use our new Fivem/Redm plugin available here: https://github.com/Top-Serveurs/cfx-vote-plugin
