### ISSUE TITLE
non réponse de l'API

### ISSUE THREAD

**Issue by KrustyCC** [Top-Serveurs/fivem-vote-plugin#9]
Bonjour, 
J'ai fais exactement comme sur le tutoriel mais je ne recois aucune réponse de l'API lorsque je fais les test vote etc. 

Pourtant j'ai bien les messages qui disent que tout est actif, j'ai bien mis le token et les votes.

Aidez moi ...

**Comment by Metrakit** [comment]
This plugin is deprecated, as explained in our documentation you have to use our new Fivem/Redm plugin available here: https://github.com/Top-Serveurs/cfx-vote-plugin
